#!/usr/bin/env python3
"""trivy_autofix.py — parse Trivy JSON outputs, bump Docker base images where possible.

Actions:
  - Parses trivy-companion.json and trivy-sidecar.json
  - Tries to bump docker:XX-cli to the latest available tag on Docker Hub
  - Writes .github/pr_body.md with CVE table + change log
  - Writes GITHUB_OUTPUT: changed=true|false
"""
import json
import os
import re
import urllib.request
import urllib.error
from pathlib import Path

GITHUB_OUTPUT = os.environ.get("GITHUB_OUTPUT", "/dev/null")

TRIVY_FILES = {
    "Companion": Path("trivy-companion.json"),
    "Sidecar":   Path("trivy-sidecar.json"),
}

DOCKERFILES = {
    "Companion": Path("Dockerfile"),
    "Sidecar":   Path("sidecar/Dockerfile"),
}


# ---------------------------------------------------------------------------
# Trivy parsing
# ---------------------------------------------------------------------------

def load_trivy(path: Path) -> dict:
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


def fixable_cves(data: dict) -> list[dict]:
    """Return deduplicated list of CVEs that have a fixed version available."""
    seen: set[str] = set()
    out: list[dict] = []
    for result in data.get("Results", []):
        for v in result.get("Vulnerabilities", []):
            cve_id = v.get("VulnerabilityID", "")
            if not v.get("FixedVersion") or cve_id in seen:
                continue
            seen.add(cve_id)
            out.append({
                "id":        cve_id,
                "pkg":       v.get("PkgName", ""),
                "installed": v.get("InstalledVersion", ""),
                "fixed":     v.get("FixedVersion", ""),
                "severity":  v.get("Severity", ""),
                "title":     v.get("Title", ""),
            })
    return out


# ---------------------------------------------------------------------------
# Docker Hub tag lookup
# ---------------------------------------------------------------------------

def _hub_tags(image: str, name_filter: str) -> list[str]:
    """Return tag names from Docker Hub matching name_filter."""
    url = (
        f"https://hub.docker.com/v2/repositories/library/{image}/tags"
        f"?name={name_filter}&page_size=20&ordering=last_updated"
    )
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            return [t["name"] for t in json.loads(r.read()).get("results", [])]
    except Exception:
        return []


def _docker_cli_version(tag: str) -> tuple[int, int, int] | None:
    """Return comparable version for docker CLI tags such as 29-cli or 29.6.0-cli."""
    match = re.fullmatch(r"(\d+)(?:\.(\d+))?(?:\.(\d+))?-cli", tag)
    if not match:
        return None
    return tuple(int(part or 0) for part in match.groups())


def latest_docker_cli_tag(current_tag: str) -> str | None:
    """
    Given a tag like '29-cli', '29.6-cli' or '29.6.0-cli', find the latest
    same-or-newer docker CLI tag on Docker Hub.
    Returns the tag name if a newer one is found, else None.
    """
    current_version = _docker_cli_version(current_tag)
    if not current_version:
        return None
    current_major = current_version[0]

    candidates: list[tuple[tuple[int, int, int], str]] = []

    # Try current+1 first (prefer upgrade), then current (patch within major)
    for try_major in (current_major + 1, current_major):
        for tag in _hub_tags("docker", str(try_major)):
            version = _docker_cli_version(tag)
            if version and version[0] >= current_major and version > current_version:
                candidates.append((version, tag))
    if not candidates:
        return None
    return max(candidates)[1]


# ---------------------------------------------------------------------------
# Dockerfile patching
# ---------------------------------------------------------------------------

def bump_docker_cli(dockerfile: Path, current_tag: str, new_tag: str) -> bool:
    """Replace FROM docker:CURRENT_TAG with FROM docker:NEW_TAG."""
    old = dockerfile.read_text()
    pattern = re.compile(
        rf"(FROM\s+docker:){re.escape(current_tag)}(\b[^\n]*)",
        re.IGNORECASE,
    )
    new = pattern.sub(lambda m: f"FROM docker:{new_tag}{m.group(2)}", old)
    if new != old:
        dockerfile.write_text(new)
        return True
    return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    changed = False
    pr_lines: list[str] = [
        "## \U0001f512 Security: Docker base image updates\n\n",
        "_Auto-generated by the [Trivy CVE scan workflow]"
        "(.github/workflows/trivy-scan.yml). "
        "CI rebuilds both images and runs a smoke test to confirm the fix is not breaking._\n\n",
    ]

    all_cves: dict[str, list[dict]] = {}

    for label, trivy_path in TRIVY_FILES.items():
        cves = fixable_cves(load_trivy(trivy_path))
        all_cves[label] = cves

        if not cves:
            pr_lines.append(f"### {label} — no fixable CVEs ✅\n\n")
            continue

        sev_icon = {"CRITICAL": "\U0001f534", "HIGH": "\U0001f7e0"}.get
        pr_lines.append(f"### {label} — {len(cves)} fixable CVE(s)\n\n")
        pr_lines.append("| Severity | CVE | Package | Installed | Fixed in |\n")
        pr_lines.append("|---|---|---|---|---|\n")
        for v in cves:
            icon = sev_icon(v["severity"], "⚠️")
            pr_lines.append(
                f"| {icon} {v['severity']} | {v['id']} | `{v['pkg']}` "
                f"| {v['installed']} | {v['fixed']} |\n"
            )
        pr_lines.append("\n")

    # ── Try to bump docker:XX-cli in Companion Dockerfile ──────────────────
    df = DOCKERFILES["Companion"]
    if df.exists() and any(all_cves.values()):
        content = df.read_text()
        m = re.search(r"FROM\s+docker:([\w.\-]+)", content, re.IGNORECASE)
        if m:
            current_tag = m.group(1)
            if "cli" in current_tag:
                print(f"Current Docker CLI tag: docker:{current_tag}")
                latest = latest_docker_cli_tag(current_tag)
                if latest and latest != current_tag:
                    print(f"Bumping docker:{current_tag} → docker:{latest}")
                    if bump_docker_cli(df, current_tag, latest):
                        changed = True
                        pr_lines.append(
                            f"**Companion `Dockerfile` change:** "
                            f"`docker:{current_tag}` → `docker:{latest}`\n\n"
                        )
                else:
                    pr_lines.append(
                        f"> ⚠️ No newer `docker:*cli` tag found on Docker Hub "
                        f"(current: `docker:{current_tag}`). Manual review required.\n\n"
                    )

    if not changed:
        pr_lines.append(
            "> ℹ️ No automatic Dockerfile changes were made. "
            "Review the CVE table above and update pinned versions manually.\n"
        )

    pr_body = "".join(pr_lines)
    Path(".github/pr_body.md").write_text(pr_body)
    print("PR body written to .github/pr_body.md")

    with open(GITHUB_OUTPUT, "a") as f:
        f.write(f"changed={'true' if changed else 'false'}\n")

    total = sum(len(v) for v in all_cves.values())
    print(f"Fixable CVEs: {total} | Dockerfile changed: {changed}")


if __name__ == "__main__":
    main()
